In [13]:
import pickle
import matplotlib.pyplot as plt

In [202]:
database,scale_x,scale_y = pickle.load(open("db_dump.pkl","rb"))

In [5]:
import cv2

In [228]:
import metric_learn

In [252]:
label_of = {}
cur = 0
for d in database:
    if not d[2] in label_of:
        label_of[d[2]] = cur
        cur += 1

In [258]:
new_db = []
min_h,min_w = 1000,1000
for d in database:
    min_h,min_w = min(min_h,d[0].shape[0]),min(min_w,d[0].shape[1])
for d in database:
    h, w = d[0].shape[:2]
    r = (d[0][(h - min_h) // 2 : (h + min_h) // 2, (w - min_w) // 2 : (w + min_w) // 2]).astype(np.float64)
    new_db.append((r,d[2]))    

In [259]:
for d in new_db[:2]:
    print(d)

(array([[   0.,    0.,    0.,    0.,   53.,  131.,  167.,   84.,    0.,
           0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
           0.,    0.,    0.,    0.,    0.,    0.,    0.,   94.,  250.,
         250.,  250.,  250.,  250.,  250.,  140.,    0.,    0.],
       [   0.,    0.,    0.,  124.,  250.,  250.,  250.,  250.,  120.,
           0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
           0.,    0.,    0.,    0.,    0.,    0.,    0.,  182.,  250.,
         210.,  116.,  171.,  250.,  250.,  248.,   34.,    0.],
       [   0.,    0.,   37.,  244.,  250.,  250.,  250.,  250.,  244.,
         125.,    2.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
           0.,    0.,    0.,    0.,    0.,    0.,    4.,  236.,  247.,
          35.,    0.,    0.,  100.,  243.,  250.,  123.,    0.],
       [   0.,    0.,  148.,  250.,  250.,  250.,  250.,  250.,  250.,
         250.,  147.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
           0.,    0.,  

In [ ]:
lmnn = metric_learn.LMNN(k=10, learn_rate=1e-6)
X = np.array([d[0].flatten() for d in new_db])
print(X.shape)
Y = np.array([label_of[d[1]] for d in new_db])
print(len(X),len(Y))
lmnn.fit(X, Y)

(1049, 665)
1049 1049


In [251]:
lmnn.metric()

array([[  9.99654273e-01,  -4.36000716e-03,  -4.89780540e-03, ...,
          1.99711764e-03,   2.88106200e-04,   2.68899120e-04],
       [ -4.36000716e-03,   9.45015465e-01,  -6.17667681e-02, ...,
          2.51858725e-02,   3.63333930e-03,   3.39111668e-03],
       [ -4.89780540e-03,  -6.17667681e-02,   9.30614424e-01, ...,
          2.82924999e-02,   4.08150450e-03,   3.80940420e-03],
       ..., 
       [  1.99711764e-03,   2.51858725e-02,   2.82924999e-02, ...,
          1.01621658e+00,  -1.66426470e-03,  -1.55331372e-03],
       [  2.88106200e-04,   3.63333930e-03,   4.08150450e-03, ...,
         -1.66426470e-03,   9.99759912e-01,  -2.24082600e-04],
       [  2.68899120e-04,   3.39111668e-03,   3.80940420e-03, ...,
         -1.55331372e-03,  -2.24082600e-04,   9.99790856e-01]])

In [214]:
def rotate(strg,n):
    return strg[n:] + strg[:n]

In [218]:
rotate("hello",4)

'ohell'

In [237]:
database[0][0].flatten()

array([0, 0, 0, ..., 0, 0, 0], dtype=uint8)